Add an argument for disabling unused controllers
fluent/fluent-operator pull request #621
Opened 2023-03-17 11:05 UTC by Kristian-ZH

### What this PR does / why we need it:
This PR adds a new flag called `disable-component-controllers` which disabled the given component's controllers
The possible values are: `fluent-bit` and `fluentd`
The default value of the argument will be an empty string which will not break the current work of the operator and will not break its consumers.

### Which issue(s) this PR fixes:

Fixes #612

### Does this PR introduced a user-facing change?

```release-note
A new argument called disable-component-controllers is added which can turn off the unused component's controllers
```

2023-03-19 11:34 UTC, wenchajun submitted a review, later dismissed

2023-03-22 01:54 UTC, wanjunlei commented
It should not add the fluentbit CRDs to scheme when fluent-bit is disabled.

https://github.com/fluent/fluent-operator/blob/master/cmd/fluent-manager/main.go#L53

2023-03-22 05:24 UTC, benjaminhuo requested changes

2023-03-22 05:24 UTC, benjaminhuo commented on cmd/fluent-manager/main.go
> +	fluentBitComponentName = "fluent-bit"
```suggestion
	fluentBitName = "fluent-bit"
```

2023-03-22 05:24 UTC, benjaminhuo commented on cmd/fluent-manager/main.go
> +	fluentDComponentName   = "fluentd"
```suggestion
	fluentdName   = "fluentd"
```

2023-03-22 05:24 UTC, benjaminhuo commented on cmd/fluent-manager/main.go
> +	var disableComponentControllers string
```suggestion
	var disabledControllers string
```

2023-03-22 05:24 UTC, benjaminhuo commented on cmd/fluent-manager/main.go
> +	flag.StringVar(&disableComponentControllers, "disable-component-controllers", "", "Optional argument which accepts two values: fluent-bit and fluentd. It will not start the controllers related to th
```suggestion
	flag.StringVar(&disabledControllers, "disable-controllers", "", "Optional argument that accepts two values: fluent-bit and fluentd. The specific controllers will not be started if they're disabled")
```

2023-03-22 05:24 UTC, benjaminhuo commented on cmd/fluent-manager/main.go
> +	fluentBitEnabled, fluentDEnabled := true, true
```suggestion
	fluentBitEnabled, fluentdEnabled := true, true
```

2023-03-22 05:27 UTC, benjaminhuo commented
> https://github.com/fluent/fluent-operator/blob/master/cmd/fluent-manager/main.go#L53

The init runs before the main function in which the disable flag is parsed, so how to do this actually?
And the helm will still try to install the CRDs even if the controller is disabled

2023-03-22 05:27 UTC, benjaminhuo commented
> It should not add the fluentbit CRDs to scheme when fluent-bit is disabled.
> 
> https://github.com/fluent/fluent-operator/blob/master/cmd/fluent-manager/main.go#L53
@wanjunlei 
The init runs before the main function in which the disable flag is parsed, so how to do this actually?
And the helm will still try to install the CRDs even if the controller is disabled

2023-03-22 05:41 UTC, wanjunlei commented
> > It should not add the fluentbit CRDs to scheme when fluent-bit is disabled.
> > https://github.com/fluent/fluent-operator/blob/master/cmd/fluent-manager/main.go#L53
> 
> @wanjunlei The init runs before the main function in which the disable flag is parsed, so how to do this actually? And the helm will still try to install the CRDs even if the controller is disabled

Just move these codes to the main. 
The helm chart should be modified accordingly to support not installing the fluentbit CRDS.

2023-03-24 08:34 UTC, Kristian-ZH commented
All the comments should be resolved, can you please take a second look?

2023-03-25 13:26 UTC, benjaminhuo approved these changes

2023-03-25 13:27 UTC, benjaminhuo commented
@Kristian-ZH Nice move! I like the idea of moving the crds to subchart!
Thanks!

2023-03-25 13:27 UTC, merged

2023-03-25 13:31 UTC, benjaminhuo commented
@Kristian-ZH I'm going to invite you as the fluent-operator maintainer!

2023-03-27 08:09 UTC, benjaminhuo commented
@Kristian-ZH would you help to revise the install guide? https://github.com/fluent/fluent-operator#deploy-fluent-operator-with-helm